//Set Config Required
requirejs.config({
    waitSeconds: 0,
    baseUrl: "{domain}/Content/scripts/plugins",
    paths: {
        "validate": "validate/jquery.validate.min",
        "validate.aditional": "validate/jquery.validate.min",
        "validate.es": "validate/localization/messages_es",
        "jqwidgets": "jqwidgets/jqx-all-v13.2.0",
        "moment": "moment/moment-with-locales",
        "helper": "core/helper",
        "extras": "core/extras",
        "controls": "core/controls",
        "jquery": "jquery/jquery-3.5.1.min",
        "jquery.ui": "jquery.ui/jquery-ui.min",
        "fileinput": "fileinput/js/fileinput.min",
        "fileinput.es": "fileinput/js/locales/es",
        "bootstrap-select": "bootstrap-select/bootstrap-select.min",
        "alertify": "alertify/alertify",
        "echarts": "echarts/echarts",
        "datatables.net": "datatables/datatables.min",
        "datatables_buttons": "datatables/Buttons-1.6.3/js/dataTables.buttons.min",
        "datatables_buttonsHtml5": "datatables/Buttons-1.6.3/js/buttons.html5.min",
        "bootstrap": "bootstrap4/js/bootstrap.min",
        "codemirror": "codemirror/codemirror",
        "codemirror.sql": "codemirror/sql",
        "datetimepicker": "datetimepicker/datetimepicker",
        "ckeditor": "ckeditorv4/ckeditor",
        "ckeditor5": "ckeditorv5/build/ckeditor",
        "popper": "popper/popper",
        "chartjs": "chart.js/Chart",
        "sortablejs": "sortable/Sortable",
        "numeral": "numeral/min/numeral.min",
        "jstree": "jstree/jstree.min",
        "tagsinput": "bootstrap-tag-input/tagsinput",
        "fullcalendar": "fullcalendar/main.min",
        "fullcalendar.locales": "fullcalendar/locales-all.min",
        "keyboard": "keyboard/js/jquery.keyboard.min",
        "keyboard.es": "keyboard/languages/es.min",
        "idle": "idle/jquery.idle",
        "perfect.scrollbar": "p-scroll/perfect-scrollbar",
        "sidebar": "sidebar/sidebar",
        "sweetalert": "sweetalert2/sweetalert2.all.min"
    },
    shim: {
        "jquery.ui": ["jquery"],
        "inputmask": ["jquery"],
        "chartjs": ["jquery"],
        "sortablejs": ["jquery"],
        "browser": ["jquery"],
        "helper": ["jquery", "bootstrap", "md5", "validate", "validate.es", "browser", "jquery.ui"],
        "extras": ["helper"],
        "controls": ["helper"],
        "bootstrap-select": ["bootstrap"],
        "bootstrap": ["jquery", "popper"],
        "jqwidgets": ["jquery"],
        "validate": ["jquery"],
        "datetimepicker": ["jquery", "moment"],
        "codemirror.sql": ["codemirror"],
        "fileinput.es": {
            deps: ["fileinput"]
        },
        "jquery.base64": ["jquery"],
        "tagsinput": ["jquery"],
        "keyboard": ["jquery"],
        "keyboard.es": ["jquery", "keyboard"],
        "idle": ["jquery"],
        "sidebar": ["jquery"],
    },
    urlArgs: "version=08022023.1-prod"
    //urlArgs: "version=" + (new Date()).getTime()
});